### PR TITLE
new simulations

### PR DESCRIPTION
**Pull request by mumblecrust**
I edited the simulation with increasing n so that my graphs are saved in a seperate folder. 

I added a simulation that shows the U-pattern between sample mean and standard deviation.

I added a simulation that shows the volatility of the sample standard deviation from sub-samples of the original data.

Graphs will be uploaded to overleaf.

### CODE REVIEW

**Review by x0range — APPROVED** [review]
Some minor comments:
  * As I said yesterday, it feels like `sim_levy_sd_norm.R` plots 1d data in 2d. It is not that I can't live with that (and I do love fancy plots), but I would suggest to think about this and perhaps plot the histogram instead or the cdf or something thelike (in the easiest way, by just sorting the observations, I guess)
  * I would suggest a little bit more commenting in `sim_levy_sd_norm.R`, perhaps just before line 15 (stating that this generates the rv population) and before the loop in line 20 (stating that this is the sampling simulation)
  * I would also comment the plotting a bit in `sim_levy_sd_norm.R`. Maybe it is just me and my unfamiliarity with R, but just from looking at the code, it is not obvious to me what kind of plots this produces. But ideally the comments should serve to make it completely obvious what a script does even to someone who knows the language but is not familiar with the code.

**Comment by mumblecrust** [comment]
Just added a few comments like you suggested.

I will see what I can do about the graph, you are right that it would make more sense to use a histogram.

**Comment by yangjh2612** [comment]
The format of plotting is not really my taste but we can discuss this later :)

**Comment by mumblecrust** [comment]
Let me know how you want your plots to be formatted

**Comment by yangjh2612** [comment]
Looks good. 

Just a few suggestions. 

How about we use the same format for the plots? We can use  yaxt = "n", xaxt = "n" in the plot function and add sth like  axis(side = 1, lwd = 0.3, cex.axis = 0.9),  axis(side = 2, lwd = 0.3, cex.axis = .9).

Also, adding something like par(mar = c(3, 2.5, 1, 1), mgp = c(1.5, .3, 0), tck = -.01) might be useful. You can check the code for the previous plots and change yours accordingly if that makes sense. 

I really like the first set of plots (increasing mean). The second set of plots are not too clear at first glance, though. The purpose of these plots is to show that the second moment is not a reliable measure when we have a fat-tail. The way we show is to compare the volatility of the sd in both Levy and the normal. 

If you want to keep the density approach, would it be possible to keep the scale in both plots the same and also change the dots to smooth lines (or some shaded area)? We can discuss this further if you have any concerns.

**Comment by x0range** [comment]
Cool. I like the new plots.

Just three comments:
  * (I missed this one the last time.) `sim_levy_u_curve.R` is missing packages `iterators, parallel, doParallel`; these should be added to the `pacman::p_load()` command. 
  * Some comments were deleted in `sim_levy_norm.R`. I do not really understand why. I don't think this script had too many comments. Recommended is a 1:1 ratio between comments and code. I agree that some comments feel ridiculously trivial, but this is better than no comments, especially in complex code and especially in R. (For instance, just from looking at a long dplyr command block, I am usually not able to tell what format the result is. Maybe it's because I am not familiar enough with R.) Of course, comments explaining the what and the why are more desirable than comments explaining the how.
  * I have the feeling that parts 1 and 2 of `sim_levy_norm.R` might perhaps be better organized in two separate files. I am not sure though.

**Comment by mumblecrust** [comment]
- Well spotted about the packages!
- Something happened when I was working on it in my local git. I am not exactly sure what, but I noticed that RStudio was not saving to the GIT folder but somewhere else. I might have to check again to make sure that there is nothing missing,
- They were two separate files at first, but then I put them together to generate both plots on the same canvas.

**Review by yangjh2612 — APPROVED** [review]

**Pull request merged**
