### PR TITLE
Cross Validation file

### PR DESCRIPTION
**Pull request by yangjh2612**
Similar to the other fitting files. The only difference is the CV_fun where we use a n-fold cross validation. It is quite slow. It would be good to speed it up by using multi-core or sth. 

Let me know!

### CODE REVIEW

**Review by x0range — COMMENTED** [review]
I realize that this does not matter for the current computations any more because they are basically done.

But I'd like to add my usual comments:
  * The level of commenting is insufficient. 
  * The structure of the script is unconventional and therefore hard to comprehend.
  * The script is duplicating a lot of code, making the script unnecessarily long, the computations non-generalizable, and the code hard to comprehend and prone to errors in case of future changes.

**Comment by yangjh2612** [comment]
Yes, I agree. I understand that you spent a lot of time to improve our
previous main fitting script. I could've snuck the CV function into it but
didn't want to make your nice script too messy and just recycled old
script. It would be good to clean this up a bit but I was lazy as usual.
I'll try to take another stab at it once I'm done with the current
computation.

Thanks for your comments!

Best,
Jangho

**Comment by x0range** [comment]
I can help you. I was thinking, `CV_fun` should probably go into a separate file in the fittinglevy package. 

`fun_fit_levy` is mostly duplicated code with `Prod_Fitting_Levy.R` (and `Prod_Fitting_Levy_Boot.R` has almost the same function again). 
The function should probably be generalized with a bunch of parameters and should go into a file of its own. However, I also struggle when I try to define concisely what exactly the function does, which probably means that the function does too much and should be split up.

Since we agree that we will reconsider this file later, I will approve it to allow it to be merged.

**Review by x0range — APPROVED** [review]

**Comment by yangjh2612** [comment]
Yes, it makes sense. Let's talk about it once we finsih our first draft.

**Review by mumblecrust — APPROVED** [review]

**Pull request merged**
