### PR TITLE
Gmm fits

### PR DESCRIPTION
**Pull request by x0range**
* implemented fitting using GMM instead of McCulloch as per today's decision
  * ML fits not implemented yet, but should be added in the same way
  * theoretically, we could do several more; the StableEstim package has some more methods...

  * this pull request depends on #20 and #22

### CODE REVIEW

**Comment by yangjh2612** [comment]
This looks good. But since we will try different fitting methods only with a couple of subsamples and compare the performance, wouldn't it be more efficient to create a separate script instead of chaning the existing ones?

**Comment by x0range** [comment]
> ...since we will try different fitting methods only with a couple of subsamples and compare the performance, wouldn't it be more efficient to create a separate script instead of chaning the existing ones?

I agree partly regarding the changes to `Prod_Fitting_Levy.R`. Let's talk later about the specific experimental design before I implement the changes,

**Comment by yangjh2612** [comment]
Sounds good!

**Review by mumblecrust — APPROVED** [review]

**Comment by x0range** [comment]
Added file creating plots. 

@yangjh2612 Do you want to approve this now (and #20 and #22, on which this depends, too) so we can merge? Or are there still open issues?

**Review by yangjh2612 — APPROVED** [review]
Looks great. 

I like your plot a lot. We need to think about how to harmonize different plot settings at some point. (I noticed that you used ggplot2). 

Thanks!

**Comment by x0range** [comment]
Thanks for approving. If you approve #20 and #22 too, I'll merge them in order. Otherwise, this one would supersede them.

Regarding ggplot2: Yes, I do. It's a bit more flexible and it's easy to have shaded areas. Do you think the plot's look too different from the others?

**Pull request merged**
