### PR TITLE
 Adapted negative tail to decline in positive direction 

### PR DESCRIPTION
**Pull request by x0range**
... and to have the log applied in a way that is more true to the function.

Depends on #18

### CODE REVIEW

**Comment by yangjh2612** [comment]
This looks good. Thanks!

A few suggestions:

1. I think we need to change the cutoff from 10% to 5% for a visualization
purpose. So, cut_tail = 0.95 and cut_tail = 0.05 in the
fun_plot_marginal_tail and fun_plot_marginal_tail_neg functions.

2. We also need to consider changing the bin number for the tail part from
50 to 25. So, c_hist <- hist(log(c_lp), breaks = seq(min(log(c_lp)),
max(log(c_lp)), l = 50 + 1), plot = F) -> c_hist <- hist(log(c_lp), breaks
= seq(min(log(c_lp)), max(log(c_lp)), l = 25 + 1), plot = F).

These two will solve some ugly feature of the plots.

3. It seems to me that the code xaxt_labels =
round(log_Var_mode_position_shift - axTicks(1)) doesn't work for some plots
and leave no tick labels.

4. For the industry legend, we might want to stick to the alphabet index.
If we have more space, the short name that I used for the bar chart will be
also possible. But I think the alphabet index would be just fine for now.

**Comment by x0range** [comment]
Thanks for the suggestions.

  * (1./2.) I understand this suggestion to be to reduce the shown tail size to ensure that we indeed only show the tail, not the main body of the distribution. And (2.) to reduce the bin number to straighten out some of the volatility. I am not sure if it is actually the case that we currently show part of the main body. I think the only plot for which we actually seem to have a problem with the shape is the "Left Tail of Log Density of Labor Productivity". And in this case, the shapes of the distributions for Large and Very Large firms for France, Spain, and Italy are crazy enough, that I fear both changes will not make enough of a difference. I would be more worried that these two changes (reducing tail size and bin number) would deteriorate the quality of the other plots. For the case in question ("Left Tail of Log Density of Labor Productivity"): If you look at the old tail plot (the one that is currently still in the paper), you can also see this and you can also clearly see that the weird shape notwithstanding it is still part of the tail. The question is - why do we see these weird shapes? 
  * (3.) Which plot does not have ticks labels? I think in the ones I sent last night there are labels in every figure.
  * (4.) I agree 100%, I was simply too lazy to do it last night. I'll take a look at it.

**Comment by yangjh2612** [comment]
1. Generally speaking, there seems to be no clear-cut way to decide the
optimal number of bins when we plot the histogram. The weird behavior of
the left tail of the productivity seems to come from a slight bump in
several bins in the tail. The finer the bin is, the more of this problem we
will have. Since the purpose of this plot is to show a big picture of the
tail behavior, reducing the bin number won't be too much a problem, I
think. The same goes to the cut-off of the tail. By the way, I don't think
that changing the cutoff from 10 to 5 won't make other plots look worse. I
played around with the data a bit and it looks fine to me at least.

2. On the tick label, yes, I was mistaken. Things look fine. Looking at
stuff directly from Gmail was not the best idea.

Thanks!

**Review by mumblecrust — APPROVED** [review]
I can see why adding a line at the beginning would be useful, I'll do that from now on.

**Comment by x0range** [comment]
* Fixed industry plot legend
  * Changed tail sizes to 5% (minus outlier cutoff) and bin number to 25 as per @yangjh2612 suggestions
  * Merged functions for left and right tails
  * Added description at the beginning of the script
  * Switched to pacman library loading

**Comment by yangjh2612** [comment]
As we already discussed, it looks great to me.

**Comment by yangjh2612** [comment]
It looks good to me!

**Review by yangjh2612 — APPROVED** [review]

**Pull request merged**
