### PR TITLE
Productivity dispersion paper

### PR DESCRIPTION
**Pull request by yangjh2612**

### CODE REVIEW

**Review by x0range — COMMENTED** [review]
It is going to be extremely difficult to assess these scripts, because:
  * they are almost not commented
  * indentation and formatting is not consistent
  * especially in Outline.R the structure is difficult to comprehend (libraries are imported everywhere in the script, functions definitions are interspersed with non-trivial logic of the main script)

**Comment by yangjh2612** [comment]
Fair points. I’ll revise the script accordingly. Before I do that, a couple
of questions for clarification.


It is literally impossible to comment every single line. I do understand
that commenting is important for an effective cross-checking. But I don’t
think I have a clear understanding of what is the optimal level of
commenting. As you might expect, some lines of code are just too
self-explanatory if the reader knows the R language.


I do agree that indentation and formatting are not consistent, which might
be coming from the fact that I do not have a consistent indentation and
formatting style. I’ll check out your code and see if I can follow your
style.


I’ll put all libraries in the beginning (I think you meant “xtable” and “
tidyr”).  But, I don’t think I understand clearly what you meant by “functions
definitions are interspersed with non-trivial logic of the main script”
Could you give me some examples?


Thanks for your comments! I appreciate it.


Best,

Jangho

**Comment by x0range** [comment]
I did not want to make a major issue out of this. I notice that it is a lot of work to apply all recommended coding practices to these scripts. I am merely mentioning it because I am unsure how to review this since I really have great difficulty understanding what these scripts do. 

We will have to find an agreement of how to resolve this. My suggestion: We accept the pull request but each of us spends some time working on improving and commenting the code, making it readable and applying good formatting in following commits. If we are disciplined in actually doing this, we will become aware of any mistakes that might possibly be contained in them.

But since you specifically asked about style and commenting guidelines, allow me to add some notes on this:

  * I believe a general rule of thumb for commenting is that you should have about one line of comments for each line of code. This does not necessarily mean that you should comment on each line of code.

  * For instance, you would insert longer blocks on comments for each function you define in order to explain 
    1. what the function does
    2. what the arguments are (which type, which purpose)
    3. what the function returns

  * Also, it is recommended to briefly describe the purpose of the script at the beginning of the file.

  * Otherwise, it is recommended to describe the control flow on a high level, so that a person with good knowledge of the programming language but no previous understanding of the script could understand what each line in the script does.

  * It is further recommended to follow some style guide very strictly. (I am also not good at this.) One style guide for R would be this one: https://google.github.io/styleguide/Rguide.xml

  * Regarding structure: It is generally recommended to organize each script according to a strict scheme, e.g.: First library inclusions, second function definitions, third main script. (That is, it would be valid code to define a function anywhere in the code, not just in the beginning, but this would be considered bad style.)

  * It is also generally recommended to do everything as abstract as possible; e.g no hard coded column indices. (Do not choose a column by index number; instead choose columns by column name.) Other example: Do not manipulate global variables in functions, instead hand the object over to the function as an argument and return it at the end of the function.

**Comment by yangjh2612** [comment]
I updated all the files again: more comments and more structure. Please take a look at them let me know what you think

**Review by mumblecrust — COMMENTED** [review]
On  Prod_Fitting_Levy.R:
-line 43: why index 15? Looks like it's random, but thought I'd ask.

Thanks for the comments, it is much easier to follow.

On Prod_Levy_Fit_Result.R:
-line 44: I keep having to refer back to the other file to find the variables these indices refer to. Something like [[which(colname(x) == 'levy_soofi')]] would save time, and also remain useful if the order of the columns changes for whatever reason. This indexing appears throughout the two files (for example, again in 47 and 48),
-lines 50-54: how did you pick these options? Trial and error is fine, but it might be useful to have an automatic way of determining the layouts and sizes given that we are working with different sub-samples,
-lines 171-194: based off the charts you uploaded in Dropbox, I suspect there may be something wrong. Parameters for five countries are meant to be plotted, the the result is a plot with many more lines (some of them dashed). You might have already changed that, because the code does not seem to use lty=2 at any point (the option that produces the dashed lines),
-line 175: Is it possible to specify xlab = c_uni_list? That way the x-axis is labeled by the relevant category (years, firm size, industry name/code),
-line 186: you can avoid having to produce a separate plot with a legend with the option xpd = NA in the legend() function. You can then use the inset option to place the legend wherever you like on the underlying pdf. 

Two final points on plotting the parameters:
-At no point do we calculate/plot the parameters by taking the full sample. This could be useful to demonstrate an average, similar to what was in the earlier plots (where it was just an average over all the samples),
-The line graph makes sense when plotting over time, but maybe less so when plotting by firm size or industry. It might be worthwhile to have bar charts for those instead.

**Comment by yangjh2612** [comment]
On Prod_Fitting_Levy.R:
-line 43: why index 15? Looks like it's random, but thought I'd ask.

-> Sort of random. The UK which is indexed by 15, has all 20 industries.
Some others not.

Thanks for the comments, it is much easier to follow.

On Prod_Levy_Fit_Result.R:
-line 44: I keep having to refer back to the other file to find the
variables these indices refer to. Something like [[which(colname(x) ==
'levy_soofi')]] would save time, and also remain useful if the order of the
columns changes for whatever reason. This indexing appears throughout the
two files (for example, again in 47 and 48),

-> good point. I'll consider this when I take another stab at it.

-lines 50-54: how did you pick these options? Trial and error is fine, but
it might be useful to have an automatic way of determining the layouts and
sizes given that we are working with different sub-samples,

->Yes,I think most of the plot functions are the result of the trial and
error, which I think might not be avoidable.



-lines 171-194: based off the charts you uploaded in Dropbox, I suspect
there may be something wrong. Parameters for five countries are meant to be
plotted, the the result is a plot with many more lines (some of them
dashed). You might have already changed that, because the code does not
seem to use lty=2 at any point (the option that produces the dashed lines),

-> Good catch. The updated script doesn't have this problem. We just need
to update the figures on Overleaf, which I'll do in a sec.

-line 175: Is it possible to specify xlab = c_uni_list? That way the x-axis
is labeled by the relevant category (years, firm size, industry name/code),

->  If we want to use the non-numeric name of the category, we need to
change the layout of the plot significantly due to the space limit. I'll
think about your suggestion. (By the way, xlab argument is for the name of
x-axis label. To change the axis name, we need to change the label in the
"axis" function.


-line 186: you can avoid having to produce a separate plot with a legend
with the option xpd = NA in the legend() function. You can then use the
inset option to place the legend wherever you like on the underlying pdf.

-> Good suggestion!

Two final points on plotting the parameters:
-At no point do we calculate/plot the parameters by taking the full sample.
This could be useful to demonstrate an average, similar to what was in the
earlier plots (where it was just an average over all the samples),

-> I agree. I'll take a look.


-The line graph makes sense when plotting over time, but maybe less so when
plotting by firm size or industry. It might be worthwhile to have bar
charts for those instead.

-> Makes sense. I think we need to eliminate the lines for now. Let's think
about what other options we have.

**Comment by yangjh2612** [comment]
I updated the three files and added the new one for the boostrapping based on TH's previous code.

**Comment by x0range** [comment]
Thanks for updating this with extensive commenting. 

I agree that the files are much more readable now. I have no objections to merging this now (also to push ahead with developing the code with finishing the paper in mind).

However:
  1. Have the comments by @mumblecrust been addressed? (At least the issues with hard coded column indices do not seem to have been addressed.) I think, these are important comments and I agree strongly with them. Instead of hard coded indices, a construction with `which` or `match` with the proper names should be used, like `match(var_name, colnames(data))` or `match("United Kingdom", country_names)`
  2. There are still a number of minor issues: 
    1. Commenting could be more extensive. For instance the logic with the class names in `fun_fit_levy` in `Prod_Fitting_Levy.R` is still rather mysterious to me. 
    2. File descriptions are missing. Comments at the beginning of files should briefly explain what the file is for. 
    3. Function descriptions are missing. Comments at the beginning of functions (or just before the function definition) should explain the purpose of the function, the input variables and the return value. 
    4. There is still non-trivial logic at the beginning of the scripts before the function definition section. 
    5. A lot of code is repeated several times. Instead, an abstraction level should be chosen that allows the code to be called from multiple places. An example is the files `Prod_Fitting_Levy.R` and `Prod_Fitting_Levy_Boot.R` that are nearly identical. I will see what I can do about that, also since we need the same code for the fitting at Country-Sector-Year level.
    6. Commit messages are not descriptive (3 times "Add files via upload", 2 times "Update", etc.).

However, I feel that these things (except for the issues raised by @mumblecrust ) are **not** important enough to hold the pull request at this point and can be addressed in the future.

**Pull request merged**
